### ISSUE TITLE
Discrepancy in Coinbase maturity might cause hard fork

### ISSUE THREAD

**Issue by burt777** [bityecoin/coinyecoin#1]
The coinbase maturity is different from the classic wallet. Since this is part of the consensus rules, this might cause hard forks. 

The file main.h in both versions set the variable COINBASE_MATURITY to 30. 
In this wallet, [2 more variables](https://github.com/bityecoin/coinyecoin/blob/f7f215664cfcf499f1eabd18c4222e789d95b6de/src/main.h#L91-L94) are introduced: COINBASE_MATURITY_NEW and COINBASE_MATURITY_SWITCH.  

The file main.cpp uses these variables to check if all inputs of a block are mature. The lines [1526-1532](https://github.com/bityecoin/coinyecoin/blob/f7f215664cfcf499f1eabd18c4222e789d95b6de/src/main.cpp#L1526-L1532) will raise the minimal maturity causing probable disparities, where transactions (and therefore blocks) of a certain maturity will be valid to some nodes and not to others. 

I think removing these lines (and L1535) should prevent any issues. 

Do note there's a function [GetRequiredMaturityDepth()](https://github.com/bityecoin/coinyecoin/blob/f7f215664cfcf499f1eabd18c4222e789d95b6de/src/main.cpp#L1488-L1499) (not existing in the classic) that also seems to execute the same switching mechanism, but i can't find any references to it, so it looks kinda redundant to me... To make things more clear (and double-check this assumption), maybe this code should be removed too.

**Comment by nardholio** [comment]
Upgrading a protocol is not necessarily a bad thing

**Comment by bityecoin** [comment]
I'm not really sure if I'd consider this to be a "consensus" issue...

Upgrading a protocol isn't necessarily breaking the rules of block reward, block time, and max supply.  I'm not sure if what you suggest would actually cause any issues or not.  I would think the goal of a development project would be to move ahead.  Old wallets may be depreciated in time, but per your insistence the core consensus is not modified.

**Comment by bityecoin** [comment]
Complete.  Version 1.6c
